<a href="https://colab.research.google.com/github/ara42/Machine-Learning/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%EC%9C%BC%EB%A1%9C_%EC%8B%9C%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sklearn

In [4]:
print(sklearn.__version__)

1.2.2


첫 번째 머신러닝 - 붓꽃 품종 예측하기

In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
iris = load_iris()
print(iris)

In [7]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [27]:
iris_data = iris.data
print(iris_data.shape)

(150, 4)


In [9]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
import numpy as np
iris_label = iris.target

In [12]:
np.unique(iris_label,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)

In [15]:
iris_df['label'] = iris.target
display(iris_df.head(3))

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [16]:
x_train,x_test, y_train,y_test = train_test_split(iris_data,iris_label,test_size=0.2)
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [17]:
dt_clf = DecisionTreeClassifier() #모델 생성

In [18]:
dt_clf.fit(x_train,y_train) #학습

DecisionTreeClassifier()

In [19]:
pred = dt_clf.predict(x_test) #예측

In [22]:
print(pred)
print(y_test)

[2 2 0 2 2 0 0 1 1 2 0 2 0 1 1 0 0 2 2 0 1 1 0 0 1 2 1 1 0 0]
[2 2 0 1 2 0 0 2 1 2 0 2 0 1 1 0 0 2 2 0 1 1 0 0 1 2 1 1 0 0]


In [23]:
#평가
from sklearn.metrics import accuracy_score

In [25]:
#모델 평가
print(f"accuracy:{accuracy_score(pred,y_test):.4f}")

accuracy:0.9333


In [30]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


In [31]:
keys = iris_data.keys()
print("키 목록:",keys)

키 목록: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [32]:
print("feature_names의 타입:",type(iris_data.feature_names))

feature_names의 타입: <class 'list'>


In [33]:
print("feature_names의 길이:",len(iris_data.feature_names))

feature_names의 길이: 4


In [34]:
print(iris_data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
print("target_names의 타입:",type(iris_data.target_names))
print("target_names의 구조:",iris_data.target_names.shape)
print("target_names:",iris_data.target_names)

target_names의 타입: <class 'numpy.ndarray'>
target_names의 구조: (3,)
target_names: ['setosa' 'versicolor' 'virginica']


In [36]:
print("data의 타입:",type(iris_data.data))
print("data의 구조:",iris_data.data.shape)

data의 타입: <class 'numpy.ndarray'>
data의 구조: (150, 4)


In [37]:
print("target의 타입:",type(iris_data.target))
print("target의 구조:",iris_data.target.shape)

target의 타입: <class 'numpy.ndarray'>
target의 구조: (150,)


학습 데이터 세트로 예측 수행

In [38]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [39]:
iris = load_iris()
train_data = iris.data
train_label = iris.target

dt_clf = DecisionTreeClassifier() #모델 생성
dt_clf.fit(train_data,train_label)#학습
pred = dt_clf.predict(train_data)#예측
print("accuracy:",accuracy_score(pred,train_label))

accuracy: 1.0


학습 70% 테스트 30%

In [42]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [43]:
iris = load_iris()

x_train,x_test,y_train,y_test =train_test_split(
    iris.data,iris.target,test_size=0.3)

dt_clf = DecisionTreeClassifier() #모델 생성
dt_clf.fit(x_train,y_train)#학습
pred = dt_clf.predict(x_test)#예측
print("accuracy:",accuracy_score(pred,y_test))

accuracy: 0.9111111111111111


K폴드 교차 검증

In [66]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [67]:
iris = load_iris()
features = iris.data
label = iris.target
print("세트 크기:",features.shape[0])

세트 크기: 150


In [68]:
df = DecisionTreeClassifier() #모델 생성
kfold = KFold(n_splits=5)
cv_accuracy =[]
n_iter = 0

In [69]:
for train_ind, test_ind in kfold.split(features):
    x_train,x_test = features[train_ind], features[test_ind]
    y_train,y_test = label[train_ind], label[test_ind]

    df.fit(x_train,y_train) #학습
    pred = dt_clf.predict(x_test) #예측
    n_iter+=1

    acc = np.round(accuracy_score(pred,y_test),3)
    print(n_iter,"회 교차 검증 accuracy:",acc)
    cv_accuracy.append(acc)
print("평균 accuracy:",np.mean(cv_accuracy))

1 회 교차 검증 accuracy: 1.0
2 회 교차 검증 accuracy: 1.0
3 회 교차 검증 accuracy: 1.0
4 회 교차 검증 accuracy: 1.0
5 회 교차 검증 accuracy: 0.833
평균 accuracy: 0.9666


In [70]:
import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [71]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_ind,test_ind in kfold.split(iris_df):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_ind]
    label_test = iris_df['label'].iloc[test_ind]
    print("##",n_iter,"회 교차 검증")
    print("학습 데이터 분포\n",label_train.value_counts())
    print("평가 데이터 분포\n",label_test.value_counts())

## 1 회 교차 검증
학습 데이터 분포
 1    50
2    50
Name: label, dtype: int64
평가 데이터 분포
 0    50
Name: label, dtype: int64
## 2 회 교차 검증
학습 데이터 분포
 0    50
2    50
Name: label, dtype: int64
평가 데이터 분포
 1    50
Name: label, dtype: int64
## 3 회 교차 검증
학습 데이터 분포
 0    50
1    50
Name: label, dtype: int64
평가 데이터 분포
 2    50
Name: label, dtype: int64


In [73]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = iris_df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(iris_df):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = iris_df['label'].iloc[train_ind]
  label_val = iris_df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


교차 검증을 보다 간편하게 - cross_val_score()

In [74]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score,cross_validate

In [76]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

In [78]:
#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도 : ',np.round(scores,4))
print('평균 검증 정확도 : ',np.round(np.mean(scores),4))

교차 검증별 정확도 :  [0.98 0.94 0.98]
평균 검증 정확도 :  0.9667


GridSearchCV

In [79]:
x_train, x_test, y_train,y_test = train_test_split(iris.data,iris.target)

In [81]:
from IPython.utils.py3compat import decode
mds = [1,2,3]
mss = [2,3,4]
for depth in mds:
    for ms in mss:
        dt = DecisionTreeClassifier(max_depth=depth,min_samples_split=ms)
        dt.fit(x_train,y_train)
        pred = dt.predict(x_test)
        print(depth,",",ms," : acc = ",accuracy_score(y_test,pred))

1 , 2  : acc =  0.5526315789473685
1 , 3  : acc =  0.5526315789473685
1 , 4  : acc =  0.5526315789473685
2 , 2  : acc =  0.9210526315789473
2 , 3  : acc =  0.9210526315789473
2 , 4  : acc =  0.9210526315789473
3 , 2  : acc =  0.9736842105263158
3 , 3  : acc =  0.9736842105263158
3 , 4  : acc =  0.9736842105263158


In [82]:
params = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3,4]
}

In [83]:
from sklearn.model_selection import GridSearchCV

In [85]:
dt = DecisionTreeClassifier()
gs = GridSearchCV(dt, param_grid=params, cv=3, refit=True)
gs.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [86]:
gs.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [87]:
gs.best_score_

0.9732100521574206

In [88]:
model = gs.best_estimator_

In [89]:
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9736842105263158

## 데이터 전처리

In [90]:
from sklearn.preprocessing import LabelEncoder

In [100]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [92]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("after:",labels)

after: [0 1 4 5 3 3 2 2]


In [93]:
items2 = ['TV','TV','냉장고','선풍기']
labels = encoder.transform(items2)
labels

array([0, 0, 1, 3])

In [ ]:
#안 됨
items2 = ['식기세척기','스타일러','슈즈스타일러']
labels = encoder.transform(items2)
labels

One-Hot Encoding

In [95]:
from sklearn.preprocessing import OneHotEncoder

In [102]:
items = np.array(items).reshape(-1,1) #2차원 배열로 변환
ohe = OneHotEncoder()
ohe.fit(items)
labels = ohe.transform(items)
print(labels.toarray())
print(labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [103]:
from scipy import stats

In [104]:
heights = stats.norm.rvs(loc=173,scale=4,size=1000)
bmis = stats.norm.rvs(loc=21,scale=2,size=1000)
weights = bmis*(heights**2)/10000

In [105]:
c_sizes = [ (heights[i]*2+weights[i]*2)/5  for i in range(1000)]
c_sizes = np.array(c_sizes)

In [106]:
from sklearn.neighbors import KNeighborsRegressor

In [107]:
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values

In [110]:
label = c_sizes

In [111]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [112]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [113]:
knn.score(x_test,y_test)

0.9962169553893349

피처 스케일링과 정규화

In [122]:
df = pd.DataFrame(data = iris.data, columns=iris.feature_names)

In [123]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [124]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [125]:
ss = StandardScaler()
ss.fit(df)
scaled = ss.transform(df)
np.round(scaled.mean(),10), scaled.var()

(-0.0, 1.0)

In [128]:
df2 = pd.DataFrame(scaled)
filter = df2[0]<-3
filter.value_counts()

False    150
Name: 0, dtype: int64

In [127]:
mms = MinMaxScaler()
mms.fit(iris_df)
scaled = mms.transform(iris_df)
df3 = pd.DataFrame(scaled)
df3.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     0.428704    0.440556    0.467458    0.458056
std      0.230018    0.181611    0.299203    0.317599
min      0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.541667    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [129]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9940284825879747

In [130]:
x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)

In [132]:
mms1 = MinMaxScaler()
mms1.fit(x_train)
scaled_train = mms1.transform(x_train)

In [133]:
mms2 = MinMaxScaler()
mms2.fit(x_test)
scaled_test = mms2.transform(x_test)

In [137]:
#fit이 다르기 때문에 결과값이 달라짐
sample = [[1.75,89],[1.72,62]]
print(mms1.transform(sample))
print(mms2.transform(sample))

[[ 1.80907408 89.62078232]
 [ 1.77671111 62.4324551 ]]
[[  2.00238133 101.32073124]
 [  1.96805479  70.54050689]]
