<a href="https://colab.research.google.com/github/ara42/Machine-Learning/blob/main/%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%B6%84%EC%84%9D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from nltk import sent_tokenize
import nltk

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
text_sample = """\
The Matrix is everywhere its all around us, here even in this room.
You can see it out your window or on your television.
You feel it when you go to work, or go to church or pay your taxes."""

In [5]:
sentences = sent_tokenize(text_sample)
print(type(sentences))
print(len(sentences))
print(sentences)

<class 'list'>
3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [6]:
from nltk import word_tokenize

In [7]:
word_tokenize(sentences[0])

['The',
 'Matrix',
 'is',
 'everywhere',
 'its',
 'all',
 'around',
 'us',
 ',',
 'here',
 'even',
 'in',
 'this',
 'room',
 '.']

In [8]:
def tokenize_text(text):
    sentences = sent_tokenize(text)
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

In [9]:
word_tokens = tokenize_text(text_sample)
print(type(word_tokens))
print(len(word_tokens))
print(word_tokens)

<class 'list'>
3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [24]:
sws = nltk.corpus.stopwords.words('english')
print('영어 stop words 개수:',len(sws))
print(sws[:20])

영어 stop words 개수: 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [25]:
all_tokens =[]
for sentence_token in word_tokens:
    fws = []
    for word in sentence_token:
        word = word.lower()
        if word not in sws:
            fws.append(word)
    all_tokens.append(fws)
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


In [26]:
from nltk.stem import LancasterStemmer

In [27]:
stemmer = LancasterStemmer()

In [31]:
print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))

work work work


In [28]:
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))

amus amus amus


In [29]:
print(stemmer.stem('happier'),stemmer.stem('happiest'))

happy happiest


In [30]:
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

fant fanciest


In [32]:
from nltk.stem import WordNetLemmatizer

In [33]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [34]:
lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v')) #amusing의 동사원형 추출

amuse


In [35]:
print(lemma.lemmatize('happiest','a'))

happy


## BOW

In [36]:
import numpy as np

In [38]:
dense = np.array([[3,0,1],[0,2,0]])

In [39]:
from scipy import sparse

In [42]:
#희소행렬 (메모리 절약 가능)
data = np.array([3,1,2])
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])
sc = sparse.coo_matrix((data,(row_pos,col_pos)))
sc.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [43]:
dense2 = np.array(
    [[0,0,1,0,0,5],
     [1,4,0,3,2,5],
     [0,6,0,3,0,0],
     [2,0,0,0,0,0],
     [0,0,0,7,0,8],
     [1,0,0,0,0,0]]
)
#COO
data2 = [1,5,1,4,3,2,5,6,3,2,7,8,1]
row_pos = [0,0,1,1,1,1,1,2,2,3,4,4,5]
col_pos = [2,5,0,1,3,4,5,1,3,0,3,5,1]
sc = sparse.coo_matrix((data2, (row_pos,col_pos)))
print(sc.toarray())

#CSR
row_pos_ind = [0,2,7,9,10,12,13]
rs = sparse.csr_matrix((data2, col_pos, row_pos_ind))
print(rs.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [0 1 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [0 1 0 0 0 0]]


## 20 뉴스그룹 분류

In [44]:
from sklearn.datasets import fetch_20newsgroups

In [45]:
news_data = fetch_20newsgroups(subset='all')

In [46]:
news_data.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [48]:
np.unique(news_data.target, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([799, 973, 985, 982, 963, 988, 975, 990, 996, 994, 999, 991, 984,
        990, 987, 997, 910, 940, 775, 628]))

In [47]:
news_data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [49]:
news_data.data[0]

"From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"

In [50]:
news_data.target[0]

10

In [51]:
news_data.target_names[10]

'rec.sport.hockey'

In [56]:
train_news = fetch_20newsgroups(subset='train',
                               remove=('headers',
                                       'footers',
                                       'quotes'))
x_train = train_news.data
y_train = train_news.target

In [53]:
x_train[0]

'I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.'

In [57]:
test_news = fetch_20newsgroups(subset='test',
                               remove=('headers',
                                       'footers',
                                       'quotes'))
x_test = test_news.data
y_test = test_news.target

In [58]:
len(x_train), len(x_test)

(11314, 7532)

In [59]:
#위의 방식 말고 한번에 받아와서 train_test_split 사용하여 분리도 가능
all_news = fetch_20newsgroups(subset='all',
                               remove=('headers',
                                       'footers',
                                       'quotes'))
data = all_news.data
label = all_news.target

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [62]:
len(x_train), len(x_test)

(14134, 4712)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [64]:
cv = CountVectorizer()
cv.fit(data)
x_train_cv = cv.transform(x_train)
x_test_cv = cv.transform(x_test)

In [66]:
x_train_cv.shape

(14134, 134410)

In [67]:
x_test_cv.shape

(4712, 134410)

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [69]:
model = LogisticRegression()
model.fit(x_train_cv,y_train)
pred = model.predict(x_test_cv)
print(accuracy_score(y_test,pred))

0.6801782682512734


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [71]:
tv = TfidfVectorizer()
tv.fit(data)
x_train_tv = tv.transform(x_train)
x_test_tv = tv.transform(x_test)

model = LogisticRegression()
model.fit(x_train_tv,y_train)
pred = model.predict(x_test_tv)
print(accuracy_score(y_test,pred))

0.7253820033955858


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [72]:
from sklearn.model_selection import GridSearchCV

In [75]:
params = {'C':[0.001,0.01,0.1,1,5,10]}
model = LogisticRegression()
gs = GridSearchCV(model,param_grid=params,cv=5,scoring='accuracy')
gs.fit(x_train_tv,y_train)
print(gs.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

{'C': 5}


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [76]:
pred = gs.predict(x_test_tv)
print(accuracy_score(y_test,pred))

0.7440577249575552
