<a href="https://colab.research.google.com/github/ara42/Machine-Learning/blob/main/%ED%8F%89%EA%B0%80_%EB%8F%84%EA%B5%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 정확도(accuracy)

In [ ]:
from sklearn.base import BaseEstimator
import numpy as np
import pandas as pd

In [ ]:
#학습을 하지 않고 예측을 하는 이상한 함수
class MYDummyClassifier(BaseEstimator):
    def fit(self,x,y=None):
        pass
    def predict(self,x):
        pred = np.zeros((x.shape[0],1))
        for i in range(x.shape[0]):
            if x['Sex'].iloc[i]==0:
                pred[i]=0
            else:
                pred[i]=1
        return pred

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/Machine-Learning/train_titanic.csv"
df = pd.read_csv(path)

In [ ]:
label = df['Survived']
data = df[['Pclass','Sex','SibSp','Parch','Fare']]

In [ ]:
data['Sex'] = pd.get_dummies(data['Sex'])['female'].values

<ipython-input-15-bb01d747e6f8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sex'] = pd.get_dummies(data['Sex'])['female'].values


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(data,label)

In [ ]:
model = MYDummyClassifier()
model.fit(x_train, y_train)

In [ ]:
pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,pred)

0.8116591928251121

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
digits = load_digits()

In [ ]:
np.unique(digits.target,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180]))

In [ ]:
data = digits.data
label = (digits.target==7).astype(int)

In [ ]:
np.unique(label,return_counts=True)

(array([0, 1]), array([1618,  179]))

In [ ]:
class MySecondClassifier(BaseEstimator):
    def fit(self,x,y=None):
        pass
    def predict(self,x):
        return np.zeros((len(x),1),dtype=bool)

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(data,label)

In [ ]:
model = MySecondClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9022222222222223

In [ ]:
d = data[0].reshape(8,-1)
d

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
for y in range(8):
    for x in range(8):
        if d[y][x] != 0:
            print("■",end="")
        else:
            print("  ",end="")
    print()

    ■■■■    
    ■■■■■  
  ■■■  ■■  
  ■■    ■■  
  ■■    ■■  
  ■■  ■■■  
  ■■■■■    
    ■■■      


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
accuracy_score(y_test,pred)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9977777777777778

## 오차 행렬

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
confusion_matrix(y_test,pred)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[406,   0],
       [  1,  43]])

In [ ]:
model = MySecondClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
confusion_matrix(y_test,pred)

array([[406,   0],
       [ 44,   0]])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
def model_evaluate(actual, pred, print_flag=True):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(actual, pred)
    precision = precision_score(actual, pred)
    recall = recall_score(actual, pred)
    if print_flag:
        print(f'accuracy : {accuracy:.3f}')
        print(f'precision : {precision:.3f}')
        print(f'recall : {recall:.3f}')
    return confusion, accuracy, precision, recall

In [ ]:
model = MySecondClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [ ]:
_,acc,_,_ = model_evaluate(y_test,pred, print_flag=False)
acc

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.9022222222222223

In [ ]:
model_evaluate(y_test,pred)

accuracy : 0.902
precision : 0.000
recall : 0.000


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(array([[406,   0],
        [ 44,   0]]),
 0.9022222222222223,
 0.0,
 0.0)

In [ ]:
label = df['Survived']
data = df[['Pclass','Sex','SibSp','Parch','Fare']]
data['Sex'] = pd.get_dummies(data['Sex'])['female'].values

<ipython-input-50-03841b96478e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sex'] = pd.get_dummies(data['Sex'])['female'].values


In [ ]:
x_train,x_test, y_train, y_test = train_test_split(data,label)

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
re = model_evaluate(y_test,pred, print_flag=True)

accuracy : 0.803
precision : 0.725
recall : 0.725


In [ ]:
model = MYDummyClassifier()
model.fit(x_train, y_train)
pred = model.predict(x_test)
re = model_evaluate(y_test,pred)

accuracy : 0.794
precision : 0.718
recall : 0.700


In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)
pred_proba = model.predict_proba(x_test)
pred_proba.shape

(223, 2)

In [ ]:
pred_proba[0], pred[0]

(array([0.87516626, 0.12483374]), array([0.]))

In [ ]:
from sklearn.preprocessing import Binarizer

In [ ]:
x = [[1,2,1],
     [4,0,2],
     [1,2,3]]
binar = Binarizer(threshold=2)
bx = binar.fit_transform(x)
bx

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [ ]:
binar = Binarizer(threshold=0.3)
ppx = binar.fit_transform(pred_proba)
ppx

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.

In [ ]:
ct = 0.5
pp1 = pred_proba[:,1].reshape(-1,1) #1인 부분만 뽑아옴
bn = Binarizer(threshold=ct)
cp = bn.fit_transform(pp1)
d = model_evaluate(y_test, cp)

accuracy : 0.803
precision : 0.725
recall : 0.725


In [ ]:
ct = 0.4
pp1 = pred_proba[:,1].reshape(-1,1) #1인 부분만 뽑아옴
bn = Binarizer(threshold=ct)
cp = bn.fit_transform(pp1)
d = model_evaluate(y_test, cp)

accuracy : 0.753
precision : 0.617
recall : 0.825


In [ ]:
def get_eval_by_thresholds(y_test,pred,thresholds):
    for threshold in thresholds:
        print("===threshold : ",threshold)
        binar = Binarizer(threshold=threshold)
        pv = binar.fit_transform(pp1)
        model_evaluate(y_test, pv)

In [ ]:
tvs = [0.4, 0.45, 0.5, 0.55, 0.6]
get_eval_by_thresholds(y_test,pp1,tvs)
#precision이 제일 높은걸 채택

===threshold :  0.4
accuracy : 0.753
precision : 0.617
recall : 0.825
===threshold :  0.45
accuracy : 0.785
precision : 0.690
recall : 0.725
===threshold :  0.5
accuracy : 0.803
precision : 0.725
recall : 0.725
===threshold :  0.55
accuracy : 0.807
precision : 0.740
recall : 0.713
===threshold :  0.6
accuracy : 0.812
precision : 0.764
recall : 0.688
